#!/bin/bash 

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/libs/i386
JRE_HOME=/usr/lib/jvm/java-6-sun/jre
CLASSPATH=$JRE_HOME/lib/j3dcore.jar:$JRE_HOME/lib/j3dutils.jar:$JRE_HOME/lib/vecmath.jar:$PWD/libs/commons-io-2.4.jar:$PWD/libs/stdlib.jar:$PWD/bin

cd bin
[ -L ds ] || ln -s ../ds
#$LD_LIBRARY_PATH 
java -cp $CLASSPATH net.iubris.aa.spheres.SVMain
